/** Public API surface for the artifact engine. */

export * from "./types.ts";
export {
  EngineError,
  validateSlug,
  validateDescription,
  hashContent,
  hashFile,
  safeRelativePath,
  ensureWithin,
  nextIndex,
  manifestPath,
  taskDirFor,
  loadManifest,
  saveManifest,
  createTask,
  tryLoadManifest,
  openTask,
  migrateManifest,
  runMigration,
  findArtifact,
  readArtifact,
  validateFlow,
  createArtifact,
  updateArtifact,
  setArtifactStatus,
  approve,
  assertStatusTransition,
  resolvePrecedence,
  changeFlow,
  setBaseBranch,
  recordRunId,
  recordTaskRun,
  recordPhaseCommit,
  fileExists,
} from "./engine.ts";
export type {
  OpenTaskResult,
  CreateTaskInput,
  CreateArtifactInput,
  CreateArtifactResult,
} from "./engine.ts";
